'use client';

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useRouter } from 'next/navigation';
import {
  Users,
  TrendingUp,
  BarChart3,
  Loader2,
  Plus,
  Archive,
  MessageCircle,
  AlertTriangle,
  CheckCircle,
  Calendar,
  Sparkles,
  RefreshCw,
  Zap,
  Brain,
  Lightbulb,
  HelpCircle,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';

interface CorrelationEvent {
  event: string;
  success_count: number;
  failure_count: number;
  odds_ratio: number;
  correlation_type: 'success' | 'failure';
  success_percentage: number;
  failure_percentage: number;
}

interface DeepAnalysis {
  lastEvents?: Array<{ event: string; count: number }>;
  lastPages?: Array<{ page: string; count: number }>;
  errors?: Array<{ event: string; message?: string; elementText?: string }>;
  devices?: Array<{ browser: string; deviceType: string; os: string; userCount: number }>;
  analyzedUsers?: number;
}

interface CohortStatistics {
  geoDistribution?: Record<string, number>;
  deviceDistribution?: Record<string, number>;
  acquisitionDistribution?: Record<string, number>;
  avgSessionDuration?: number;
  avgSignalWeight?: number;
}

interface CohortCriteria {
  autoGenerated?: boolean;
  pattern?: string;
  category?: string;
  detectedAt?: string;
  signalTypes?: string[];
  statistics?: CohortStatistics;
  topInsights?: string[];
  // Funnel cohort properties
  source?: 'funnel' | string;
  funnelId?: number;
  stepIndex?: number;
  stepName?: string;
  cohortType?: 'converted' | 'dropped';
  posthogCohortId?: number;
  userIds?: string[];
  conversionRate?: number;
  dropOffRate?: number;
  correlations?: CorrelationEvent[];
  analysis?: DeepAnalysis;
}

interface Cohort {
  id: string;
  name: string;
  description?: string;
  size: number;
  criteria?: CohortCriteria;
  createdAt: string;
  _count?: {
    analyses: number;
    interviews: number;
    members?: number;
    hypotheses?: number;
  };
  memberCount?: number;
  hypothesesCount?: number;
}

interface AutoCohort extends Cohort {
  pattern?: string;
  category?: string;
  topInsights?: string[];
}

interface CohortAnalysis {
  id: string;
  analysisType: string;
  metrics: {
    totalUsers?: number;
    avgEventsPerUser?: number;
    topEvents?: { event: string; count: number }[];
  };
  insights?: {
    summary?: string;
    trends?: string[];
    recommendations?: string[];
  };
  createdAt: string;
}

interface InterviewQuestion {
  id: string;
  question: string;
  purpose?: string;
  category?: string;
  priority: number;
}

interface Hypothesis {
  id: string;
  title: string;
  description: string;
  behaviorPattern?: any;
  confidence: number;
  evidence?: any;
  status: string;
  questions: InterviewQuestion[];
  createdAt: string;
}

export default function CohortsPage() {
  const router = useRouter();
  const [cohorts, setCohorts] = useState<Cohort[]>([]);
  const [selectedCohort, setSelectedCohort] = useState<Cohort | null>(null);
  const [analyses, setAnalyses] = useState<CohortAnalysis[]>([]);
  const [hypotheses, setHypotheses] = useState<Hypothesis[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [projectId, setProjectId] = useState<string>('');
  const [error, setError] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [autoCohorts, setAutoCohorts] = useState<AutoCohort[]>([]);
  const [isGeneratingAuto, setIsGeneratingAuto] = useState(false);
  const [refreshingCohortId, setRefreshingCohortId] = useState<string | null>(null);
  const [isGeneratingHypotheses, setIsGeneratingHypotheses] = useState(false);
  const [expandedHypothesis, setExpandedHypothesis] = useState<string | null>(null);

  useEffect(() => {
    const initializeProject = async () => {
      let currentProjectId = localStorage.getItem('currentProjectId');

      // If no project in localStorage, try to fetch and auto-select one
      if (!currentProjectId) {
        try {
          const response = await fetch('/api/projects');
          const data = await response.json();
          if (data.projects && data.projects.length > 0) {
            currentProjectId = data.projects[0].id;
            localStorage.setItem('currentProjectId', currentProjectId as string);
            console.log('Auto-selected project:', currentProjectId);
          }
        } catch (err) {
          console.error('Failed to fetch projects:', err);
        }
      }

      if (!currentProjectId) {
        setError('No project found. Please create a project first.');
        setIsLoading(false);
        return;
      }

      setProjectId(currentProjectId);
      await Promise.all([
        loadCohorts(currentProjectId),
        loadAutoCohorts(currentProjectId),
      ]);
    };

    initializeProject();
  }, []);

  const loadCohorts = async (projId: string) => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await fetch(`/api/cohorts?projectId=${projId}`);
      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to load cohorts');
      }

      setCohorts(data.cohorts || []);

      // Auto-select first cohort if available
      if (data.cohorts && data.cohorts.length > 0 && !selectedCohort) {
        await loadCohortDetails(data.cohorts[0].id, projId);
      }
    } catch (error: any) {
      console.error('Failed to load cohorts:', error);
      setError(error.message || 'Failed to load cohorts');
    } finally {
      setIsLoading(false);
    }
  };

  const loadAutoCohorts = async (projId: string) => {
    try {
      const response = await fetch(`/api/auto-cohorts?projectId=${projId}`);
      const data = await response.json();

      if (response.ok) {
        setAutoCohorts(data.cohorts || []);
      }
    } catch (error) {
      console.error('Failed to load auto-cohorts:', error);
    }
  };

  const generateAutoCohorts = async () => {
    if (!projectId) return;

    setIsGeneratingAuto(true);
    setError(null);

    try {
      const response = await fetch('/api/auto-cohorts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ projectId }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to generate auto-cohorts');
      }

      setSuccessMessage(data.message || 'Auto-cohorts generated successfully');
      setTimeout(() => setSuccessMessage(null), 5000);

      // Reload both lists
      await Promise.all([
        loadCohorts(projectId),
        loadAutoCohorts(projectId),
      ]);
    } catch (error: any) {
      console.error('Failed to generate auto-cohorts:', error);
      setError(error.message || 'Failed to generate auto-cohorts');
      setTimeout(() => setError(null), 5000);
    } finally {
      setIsGeneratingAuto(false);
    }
  };

  const refreshAutoCohort = async (cohortId: string) => {
    setRefreshingCohortId(cohortId);
    setError(null);

    try {
      const response = await fetch('/api/auto-cohorts', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ cohortId }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to refresh cohort');
      }

      setSuccessMessage(data.message || 'Cohort refreshed successfully');
      setTimeout(() => setSuccessMessage(null), 5000);

      await loadAutoCohorts(projectId);
    } catch (error: any) {
      console.error('Failed to refresh cohort:', error);
      setError(error.message || 'Failed to refresh cohort');
      setTimeout(() => setError(null), 5000);
    } finally {
      setRefreshingCohortId(null);
    }
  };

  const getPatternBadge = (pattern?: string) => {
    switch (pattern) {
      case 'churn_risk':
        return { label: 'Churn Risk', color: 'bg-red-100 text-red-700 border-red-200' };
      case 'low_engagement':
        return { label: 'Low Engagement', color: 'bg-amber-100 text-amber-700 border-amber-200' };
      case 'error_prone':
        return { label: 'Error Prone', color: 'bg-rose-100 text-rose-700 border-rose-200' };
      default:
        return { label: 'Auto', color: 'bg-purple-100 text-purple-700 border-purple-200' };
    }
  };

  const loadCohortDetails = async (cohortId: string, projId?: string) => {
    try {
      const pid = projId || projectId;
      const response = await fetch(`/api/cohorts?projectId=${pid}&cohortId=${cohortId}`);
      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to load cohort details');
      }

      setSelectedCohort(data.cohort);
      setAnalyses(data.cohort?.analyses || []);
      setHypotheses(data.cohort?.hypotheses || []);
    } catch (error: any) {
      console.error('Failed to load cohort details:', error);
      setError(error.message || 'Failed to load cohort details');
    }
  };

  const generateHypotheses = async (cohortId: string) => {
    setIsGeneratingHypotheses(true);
    setError(null);
    try {
      const response = await fetch('/api/hypotheses', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ cohortId, regenerate: true }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to generate hypotheses');
      }

      setSuccessMessage(`Generated ${data.hypothesesGenerated} hypotheses!`);
      setTimeout(() => setSuccessMessage(null), 5000);
      await loadCohortDetails(cohortId);
    } catch (error: any) {
      console.error('Failed to generate hypotheses:', error);
      setError(error.message || 'Failed to generate hypotheses');
      setTimeout(() => setError(null), 5000);
    } finally {
      setIsGeneratingHypotheses(false);
    }
  };

  const runAnalysis = async (cohortId: string) => {
    setIsAnalyzing(true);
    setError(null);
    try {
      const response = await fetch('/api/cohorts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'analyze',
          cohortId,
          analysisType: 'behavior',
          dateRange: { from: '-30d', to: 'now' },
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to run analysis');
      }

      setSuccessMessage('Analysis completed successfully!');
      setTimeout(() => setSuccessMessage(null), 5000);
      await loadCohortDetails(cohortId);
    } catch (error: any) {
      console.error('Failed to run analysis:', error);
      setError(error.message || 'Failed to run analysis');
      setTimeout(() => setError(null), 5000);
    } finally {
      setIsAnalyzing(false);
    }
  };

  const archiveCohort = async (cohortId: string) => {
    try {
      const response = await fetch(`/api/cohorts?cohortId=${cohortId}`, {
        method: 'DELETE',
      });

      if (response.ok) {
        setCohorts(prev => prev.filter(c => c.id !== cohortId));
        if (selectedCohort?.id === cohortId) {
          setSelectedCohort(null);
          setAnalyses([]);
        }
        setSuccessMessage('Cohort archived successfully');
        setTimeout(() => setSuccessMessage(null), 3000);
      }
    } catch (error) {
      console.error('Failed to archive cohort:', error);
      setError('Failed to archive cohort');
      setTimeout(() => setError(null), 5000);
    }
  };

  const scheduleInterviews = (cohortId: string) => {
    router.push(`/dashboard/interviews?cohortId=${cohortId}`);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 p-8">
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-4xl font-bold text-slate-900 tracking-tight">Cohorts</h1>
            <p className="text-slate-600 mt-2">Analyze user segments and behavior patterns</p>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={generateAutoCohorts}
              disabled={isGeneratingAuto || !projectId}
              className="flex items-center gap-2 px-5 py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-2xl hover:shadow-lg hover:shadow-purple-500/30 transition-all font-semibold disabled:opacity-50"
            >
              {isGeneratingAuto ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Brain className="w-4 h-4" />
              )}
              {isGeneratingAuto ? 'Detecting...' : 'Auto-Detect Patterns'}
            </button>
            <button
              onClick={() => router.push('/dashboard/funnels')}
              className="flex items-center gap-2 px-5 py-3 bg-gradient-to-r from-blue-600 to-cyan-600 text-white rounded-2xl hover:shadow-lg hover:shadow-blue-500/30 transition-all font-semibold"
            >
              <Plus className="w-4 h-4" />
              Create from Funnel
            </button>
          </div>
        </div>

        {/* Messages */}
        <AnimatePresence>
          {successMessage && (
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="mb-6 flex items-center gap-2 p-4 rounded-xl bg-green-50 border border-green-200 text-green-700"
            >
              <CheckCircle className="w-5 h-5" />
              {successMessage}
            </motion.div>
          )}
          {error && (
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="mb-6 flex items-center gap-2 p-4 rounded-xl bg-red-50 border border-red-200 text-red-700"
            >
              <AlertTriangle className="w-5 h-5" />
              {error}
            </motion.div>
          )}
        </AnimatePresence>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Cohorts List */}
          <div className="lg:col-span-1 space-y-4">
            {/* Auto-Generated Cohorts Section */}
            {autoCohorts.length > 0 && (
              <div className="space-y-3">
                <div className="flex items-center gap-2 text-sm font-semibold text-purple-700">
                  <Sparkles className="w-4 h-4" />
                  Auto-Detected Patterns
                </div>
                {autoCohorts.map(cohort => {
                  const badge = getPatternBadge(cohort.criteria?.pattern);
                  const category = cohort.criteria?.category;
                  const topInsight = cohort.criteria?.topInsights?.[0];
                  const stats = cohort.criteria?.statistics;
                  
                  return (
                    <motion.div
                      key={cohort.id}
                      onClick={() => loadCohortDetails(cohort.id)}
                      className={`p-4 rounded-2xl border cursor-pointer transition-all ${
                        selectedCohort?.id === cohort.id
                          ? 'bg-gradient-to-br from-purple-50 to-pink-50 border-purple-300 shadow-md'
                          : 'bg-white border-slate-200 hover:border-purple-200 hover:shadow-sm'
                      }`}
                      whileHover={{ y: -2 }}
                    >
                      <div className="flex items-start justify-between mb-2">
                        <h3 className="font-semibold text-slate-900 text-sm line-clamp-2">{cohort.name}</h3>
                        <div className="flex items-center gap-1">
                          <span className={`px-2 py-0.5 rounded-full text-xs font-medium border ${badge.color}`}>
                            {badge.label}
                          </span>
                          {category && (
                            <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                              category === 'behavioral' ? 'bg-blue-50 text-blue-600' :
                              category === 'demographic' ? 'bg-green-50 text-green-600' :
                              category === 'acquisition' ? 'bg-orange-50 text-orange-600' :
                              'bg-purple-50 text-purple-600'
                            }`}>
                              {category}
                            </span>
                          )}
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              refreshAutoCohort(cohort.id);
                            }}
                            className="p-1 text-slate-400 hover:text-purple-600 rounded transition-colors"
                            title="Refresh cohort"
                          >
                            {refreshingCohortId === cohort.id ? (
                              <Loader2 className="w-3 h-3 animate-spin" />
                            ) : (
                              <RefreshCw className="w-3 h-3" />
                            )}
                          </button>
                        </div>
                      </div>
                      
                      {/* Top Insight Preview */}
                      {topInsight && (
                        <p className="text-xs text-slate-500 mb-2 line-clamp-1 italic">
                          💡 {topInsight}
                        </p>
                      )}
                      
                      {/* Statistics Preview */}
                      {stats && (
                        <div className="flex flex-wrap gap-1 mb-2">
                          {stats.geoDistribution && Object.keys(stats.geoDistribution).length > 0 && (
                            <span className="px-1.5 py-0.5 rounded bg-slate-100 text-xs text-slate-600">
                              🌍 {Object.keys(stats.geoDistribution).length} countries
                            </span>
                          )}
                          {stats.deviceDistribution?.mobile && stats.deviceDistribution.mobile > 0 && (
                            <span className="px-1.5 py-0.5 rounded bg-slate-100 text-xs text-slate-600">
                              📱 {Math.round((stats.deviceDistribution.mobile / (cohort.size || 1)) * 100)}% mobile
                            </span>
                          )}
                          {stats.avgSessionDuration && stats.avgSessionDuration > 0 && (
                            <span className="px-1.5 py-0.5 rounded bg-slate-100 text-xs text-slate-600">
                              ⏱ {Math.round(stats.avgSessionDuration)}s avg
                            </span>
                          )}
                        </div>
                      )}
                      
                      <div className="flex items-center justify-between text-xs text-slate-500">
                        <span className="flex items-center gap-1">
                          <Users className="w-3 h-3" />
                          {cohort.memberCount || cohort.size || 0} users
                        </span>
                        <span className="flex items-center gap-1">
                          <Zap className="w-3 h-3" />
                          {cohort.hypothesesCount || cohort._count?.hypotheses || 0} hypotheses
                        </span>
                      </div>
                    </motion.div>
                  );
                })}
              </div>
            )}

            {/* Manual Cohorts Section */}
            <div className="space-y-3">
              {/* Funnel Cohorts */}
              {cohorts.filter(c => c.criteria?.source === 'funnel').length > 0 && (
                <>
                  <div className="flex items-center gap-2 text-sm font-semibold text-blue-700">
                    <TrendingUp className="w-4 h-4" />
                    Funnel Cohorts
                  </div>
                  {cohorts.filter(c => c.criteria?.source === 'funnel').map(cohort => (
                    <motion.div
                      key={cohort.id}
                      onClick={() => loadCohortDetails(cohort.id)}
                      className={`p-4 rounded-2xl border cursor-pointer transition-all ${
                        selectedCohort?.id === cohort.id
                          ? 'bg-gradient-to-br from-blue-50 to-cyan-50 border-blue-300 shadow-md'
                          : 'bg-white border-slate-200 hover:border-blue-200 hover:shadow-sm'
                      }`}
                      whileHover={{ y: -2 }}
                    >
                      <div className="flex items-start justify-between mb-1">
                        <h3 className="font-semibold text-slate-900 text-sm line-clamp-2">{cohort.name}</h3>
                        <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                          cohort.criteria?.cohortType === 'converted' 
                            ? 'bg-emerald-100 text-emerald-700' 
                            : 'bg-red-100 text-red-700'
                        }`}>
                          {cohort.criteria?.cohortType === 'converted' ? 'Converted' : 'Dropped'}
                        </span>
                      </div>
                      {cohort.description && (
                        <p className="text-xs text-slate-500 mb-2 line-clamp-2">{cohort.description}</p>
                      )}
                      <div className="flex items-center justify-between text-xs text-slate-500">
                        <span className="flex items-center gap-1">
                          <Users className="w-3 h-3" />
                          {cohort.size} users
                        </span>
                        <span className="flex items-center gap-1">
                          <BarChart3 className="w-3 h-3" />
                          {cohort._count?.analyses ?? 0} analyses
                        </span>
                      </div>
                    </motion.div>
                  ))}
                </>
              )}

              {/* Other Manual Cohorts */}
              {cohorts.filter(c => c.criteria?.source !== 'funnel' && !c.criteria?.autoGenerated).length > 0 && (
                <>
                  <div className="flex items-center gap-2 text-sm font-semibold text-slate-700">
                    <Users className="w-4 h-4" />
                    Manual Cohorts
                  </div>
                  {cohorts.filter(c => c.criteria?.source !== 'funnel' && !c.criteria?.autoGenerated).map(cohort => (
                    <motion.div
                      key={cohort.id}
                      onClick={() => loadCohortDetails(cohort.id)}
                      className={`p-4 rounded-2xl border cursor-pointer transition-all ${
                        selectedCohort?.id === cohort.id
                          ? 'bg-gradient-to-br from-blue-50 to-cyan-50 border-blue-300 shadow-md'
                          : 'bg-white border-slate-200 hover:border-blue-200 hover:shadow-sm'
                      }`}
                      whileHover={{ y: -2 }}
                    >
                      <h3 className="font-semibold text-slate-900 mb-1 line-clamp-2">{cohort.name}</h3>
                      {cohort.description && (
                        <p className="text-sm text-slate-600 mb-3 line-clamp-2">{cohort.description}</p>
                      )}
                      <div className="flex items-center justify-between text-xs text-slate-500">
                        <span className="flex items-center gap-1">
                          <Users className="w-3 h-3" />
                          {cohort.size} users
                        </span>
                        <span className="flex items-center gap-1">
                          <BarChart3 className="w-3 h-3" />
                          {cohort._count?.analyses ?? 0} analyses
                        </span>
                      </div>
                    </motion.div>
                  ))}
                </>
              )}

              {isLoading ? (
                <div className="flex justify-center py-10">
                  <Loader2 className="w-6 h-6 animate-spin text-blue-600" />
                </div>
              ) : cohorts.length === 0 && autoCohorts.length === 0 ? (
                <div className="text-center py-10 bg-white rounded-2xl border border-slate-200 shadow-sm">
                  <Users className="w-10 h-10 mx-auto mb-3 text-slate-300" />
                  <p className="text-slate-500 mb-4">No cohorts yet</p>
                  <div className="space-y-2">
                    <button
                      onClick={generateAutoCohorts}
                      disabled={isGeneratingAuto}
                      className="text-sm text-purple-600 hover:text-purple-700 font-medium block mx-auto"
                    >
                      Auto-detect patterns →
                    </button>
                    <button
                      onClick={() => router.push('/dashboard/funnels')}
                      className="text-sm text-blue-600 hover:text-blue-700 font-medium block mx-auto"
                    >
                      Create from Funnels →
                    </button>
                  </div>
                </div>
              ) : null}
            </div>
          </div>

          {/* Cohort Details */}
          <div className="lg:col-span-2">
            {selectedCohort ? (
              <div className="space-y-5">
                <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm">
                  <div className="flex items-start justify-between mb-6">
                    <div className="flex-1">
                      <h2 className="text-2xl font-bold text-slate-900">{selectedCohort.name}</h2>
                      {selectedCohort.description && (
                        <p className="text-slate-600 mt-1">{selectedCohort.description}</p>
                      )}
                      <div className="flex items-center gap-2 mt-2 text-xs text-slate-500">
                        <Calendar className="w-3 h-3" />
                        Created {new Date(selectedCohort.createdAt).toLocaleDateString()}
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => scheduleInterviews(selectedCohort.id)}
                        className="flex items-center gap-2 px-4 py-2 bg-purple-50 text-purple-600 rounded-xl hover:bg-purple-100 transition-all font-medium"
                      >
                        <MessageCircle className="w-4 h-4" />
                        Interview
                      </button>
                      <button
                        onClick={() => runAnalysis(selectedCohort.id)}
                        disabled={isAnalyzing}
                        className="flex items-center gap-2 px-4 py-2 bg-blue-50 text-blue-600 rounded-xl hover:bg-blue-100 disabled:opacity-50 transition-all font-medium"
                      >
                        {isAnalyzing ? (
                          <Loader2 className="w-4 h-4 animate-spin" />
                        ) : (
                          <BarChart3 className="w-4 h-4" />
                        )}
                        Analyze
                      </button>
                      <button
                        onClick={() => archiveCohort(selectedCohort.id)}
                        className="p-2 text-slate-400 hover:text-red-500 rounded-xl hover:bg-red-50 transition-all"
                        title="Archive cohort"
                      >
                        <Archive className="w-4 h-4" />
                      </button>
                    </div>
                  </div>

                  <div className="grid grid-cols-3 gap-4">
                    <div className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-xl p-4 border border-blue-200">
                      <div className="text-blue-600 text-sm mb-1 font-medium">Total Users</div>
                      <div className="text-3xl font-bold text-blue-900">{selectedCohort.size}</div>
                    </div>
                    <div className="bg-gradient-to-br from-purple-50 to-purple-100 rounded-xl p-4 border border-purple-200">
                      <div className="text-purple-600 text-sm mb-1 font-medium">Analyses</div>
                      <div className="text-3xl font-bold text-purple-900">{selectedCohort._count?.analyses ?? 0}</div>
                    </div>
                    <div className="bg-gradient-to-br from-cyan-50 to-cyan-100 rounded-xl p-4 border border-cyan-200">
                      <div className="text-cyan-600 text-sm mb-1 font-medium">Interviews</div>
                      <div className="text-3xl font-bold text-cyan-900">{selectedCohort._count?.interviews ?? 0}</div>
                    </div>
                  </div>

                  {/* Cohort Criteria/Source */}
                  {selectedCohort.criteria && (
                    <div className="mt-4 p-4 bg-slate-50 rounded-xl border border-slate-200">
                      <h4 className="text-sm font-semibold text-slate-700 mb-2">Source</h4>
                      <div className="text-sm text-slate-600">
                        {(selectedCohort.criteria as any).funnelName && (
                          <span>From funnel: <strong>{(selectedCohort.criteria as any).funnelName}</strong></span>
                        )}
                        {(selectedCohort.criteria as any).stepName && (
                          <span> → Step: <strong>{(selectedCohort.criteria as any).stepName}</strong></span>
                        )}
                        {(selectedCohort.criteria as any).dropOffRate && (
                          <span className="ml-2 text-red-600">({(selectedCohort.criteria as any).dropOffRate.toFixed(1)}% drop-off)</span>
                        )}
                        {(selectedCohort.criteria as any).conversionRate && (
                          <span className="ml-2 text-emerald-600">({(selectedCohort.criteria as any).conversionRate.toFixed(1)}% conversion)</span>
                        )}
                        {selectedCohort.criteria.autoGenerated && (
                          <div className="flex items-center gap-2 mt-1">
                            <Sparkles className="w-3 h-3 text-purple-500" />
                            <span>Auto-detected: <strong className="text-purple-700">{selectedCohort.criteria.pattern}</strong></span>
                            {selectedCohort.criteria.category && (
                              <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                                selectedCohort.criteria.category === 'behavioral' ? 'bg-blue-100 text-blue-700' :
                                selectedCohort.criteria.category === 'demographic' ? 'bg-green-100 text-green-700' :
                                selectedCohort.criteria.category === 'acquisition' ? 'bg-orange-100 text-orange-700' :
                                'bg-purple-100 text-purple-700'
                              }`}>
                                {selectedCohort.criteria.category}
                              </span>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  )}

                  {/* Funnel Correlation Data */}
                  {selectedCohort.criteria?.correlations && selectedCohort.criteria.correlations.length > 0 && (
                    <div className="mt-4 p-4 bg-gradient-to-br from-slate-50 to-slate-100 rounded-xl border border-slate-200">
                      <h4 className="text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2">
                        <TrendingUp className="w-4 h-4" />
                        {selectedCohort.criteria.cohortType === 'dropped' 
                          ? 'Events Correlated with Drop-off' 
                          : 'Events Correlated with Conversion'}
                      </h4>
                      <p className="text-xs text-slate-500 mb-3">
                        {selectedCohort.criteria.cohortType === 'dropped'
                          ? 'Higher ratio (>1) = stronger correlation with drop-off. These events indicate friction points.'
                          : 'Lower ratio (≤1) = stronger correlation with conversion. These events indicate success patterns.'}
                      </p>
                      <div className="border border-slate-200 rounded-lg overflow-hidden bg-white">
                        {/* Table header */}
                        <div className="grid grid-cols-[1fr_80px_80px_60px] gap-2 px-3 py-2 bg-slate-50 border-b border-slate-200 text-xs font-medium text-slate-500">
                          <span>Event</span>
                          <span className="text-right">Dropped %</span>
                          <span className="text-right">Converted %</span>
                          <span className="text-right">Ratio</span>
                        </div>
                        
                        {/* Rows */}
                        {selectedCohort.criteria.correlations.slice(0, 8).map((correlation: CorrelationEvent, idx: number) => (
                          <div
                            key={idx}
                            className={`grid grid-cols-[1fr_80px_80px_60px] gap-2 px-3 py-2.5 items-center ${
                              idx !== Math.min(selectedCohort.criteria!.correlations!.length, 8) - 1 ? 'border-b border-slate-100' : ''
                            } hover:bg-slate-50/50 transition-colors`}
                          >
                            <div className="min-w-0">
                              <span className="font-mono text-sm text-slate-800 truncate block">
                                {correlation.event}
                              </span>
                            </div>
                            <span className="text-right text-sm tabular-nums text-slate-600">
                              {correlation.failure_percentage.toFixed(0)}%
                            </span>
                            <span className="text-right text-sm tabular-nums text-slate-600">
                              {correlation.success_percentage.toFixed(0)}%
                            </span>
                            <span className={`text-right text-sm font-semibold tabular-nums ${
                              correlation.odds_ratio > 1 ? 'text-red-600' : 'text-emerald-600'
                            }`}>
                              {correlation.odds_ratio.toFixed(2)}×
                            </span>
                          </div>
                        ))}
                      </div>
                      {selectedCohort.criteria.correlations.length > 8 && (
                        <p className="text-xs text-slate-400 mt-2 text-center">
                          +{selectedCohort.criteria.correlations.length - 8} more correlations
                        </p>
                      )}
                    </div>
                  )}

                  {/* Deep Analysis Data */}
                  {selectedCohort.criteria?.analysis && (
                    <div className="mt-4 grid grid-cols-2 gap-3">
                      {/* Last Events */}
                      {selectedCohort.criteria.analysis.lastEvents && selectedCohort.criteria.analysis.lastEvents.length > 0 && (
                        <div className="p-4 bg-gradient-to-br from-amber-50 to-orange-50 rounded-xl border border-amber-200">
                          <h4 className="text-sm font-semibold text-amber-700 mb-2 flex items-center gap-1">
                            ⭐ Last Events Before {selectedCohort.criteria.cohortType === 'dropped' ? 'Drop-off' : 'Conversion'}
                          </h4>
                          <div className="space-y-1">
                            {selectedCohort.criteria.analysis.lastEvents.slice(0, 5).map((item, idx) => (
                              <div key={idx} className="flex items-center justify-between text-sm">
                                <span className="text-slate-600 font-mono text-xs truncate max-w-[150px]">{item.event}</span>
                                <span className="font-medium text-amber-700">{item.count} users</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {/* Last Pages */}
                      {selectedCohort.criteria.analysis.lastPages && selectedCohort.criteria.analysis.lastPages.length > 0 && (
                        <div className="p-4 bg-gradient-to-br from-blue-50 to-cyan-50 rounded-xl border border-blue-200">
                          <h4 className="text-sm font-semibold text-blue-700 mb-2 flex items-center gap-1">
                            🌐 Last Pages Visited
                          </h4>
                          <div className="space-y-1">
                            {selectedCohort.criteria.analysis.lastPages.slice(0, 5).map((item, idx) => (
                              <div key={idx} className="flex items-center justify-between text-sm">
                                <span className="text-slate-600 font-mono text-xs truncate max-w-[150px]" title={item.page}>{item.page}</span>
                                <span className="font-medium text-blue-700">{item.count}</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {/* Errors */}
                      {selectedCohort.criteria.analysis.errors && selectedCohort.criteria.analysis.errors.length > 0 && (
                        <div className="p-4 bg-gradient-to-br from-red-50 to-rose-50 rounded-xl border border-red-200">
                          <h4 className="text-sm font-semibold text-red-700 mb-2 flex items-center gap-1">
                            ⚠️ Errors & Frustration
                          </h4>
                          <div className="space-y-1">
                            {selectedCohort.criteria.analysis.errors.slice(0, 4).map((error, idx) => (
                              <div key={idx} className="text-xs">
                                <span className={`px-1.5 py-0.5 rounded font-medium ${
                                  error.event === '$exception' ? 'bg-red-100 text-red-700' :
                                  error.event === '$rageclick' ? 'bg-orange-100 text-orange-700' :
                                  'bg-amber-100 text-amber-700'
                                }`}>
                                  {error.event === '$exception' ? 'Error' : error.event === '$rageclick' ? 'Rage Click' : 'Dead Click'}
                                </span>
                                {error.elementText && (
                                  <span className="text-slate-500 ml-1">on &quot;{error.elementText}&quot;</span>
                                )}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {/* Devices */}
                      {selectedCohort.criteria.analysis.devices && selectedCohort.criteria.analysis.devices.length > 0 && (
                        <div className="p-4 bg-gradient-to-br from-violet-50 to-purple-50 rounded-xl border border-violet-200">
                          <h4 className="text-sm font-semibold text-violet-700 mb-2 flex items-center gap-1">
                            💻 Device & Browser
                          </h4>
                          <div className="space-y-1">
                            {selectedCohort.criteria.analysis.devices.slice(0, 4).map((device, idx) => (
                              <div key={idx} className="flex items-center justify-between text-sm">
                                <span className="text-slate-600 text-xs">{device.browser} / {device.os}</span>
                                <span className="font-medium text-violet-700">{device.userCount}</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  )}

                  {/* Rich Statistics from Persons API */}
                  {selectedCohort.criteria?.statistics && (
                    <div className="mt-4 grid grid-cols-2 gap-3">
                      {/* Geo Distribution */}
                      {selectedCohort.criteria.statistics.geoDistribution && 
                       Object.keys(selectedCohort.criteria.statistics.geoDistribution).length > 0 && (
                        <div className="p-4 bg-gradient-to-br from-emerald-50 to-teal-50 rounded-xl border border-emerald-200">
                          <h4 className="text-sm font-semibold text-emerald-700 mb-2 flex items-center gap-1">
                            🌍 Geographic Distribution
                          </h4>
                          <div className="space-y-1">
                            {Object.entries(selectedCohort.criteria.statistics.geoDistribution)
                              .sort(([,a], [,b]) => b - a)
                              .slice(0, 5)
                              .map(([country, count]) => (
                                <div key={country} className="flex items-center justify-between text-sm">
                                  <span className="text-slate-600">{country}</span>
                                  <span className="font-medium text-emerald-700">
                                    {count} ({Math.round((count / selectedCohort.size) * 100)}%)
                                  </span>
                                </div>
                              ))}
                          </div>
                        </div>
                      )}

                      {/* Device Distribution */}
                      {selectedCohort.criteria.statistics.deviceDistribution && 
                       Object.keys(selectedCohort.criteria.statistics.deviceDistribution).length > 0 && (
                        <div className="p-4 bg-gradient-to-br from-violet-50 to-purple-50 rounded-xl border border-violet-200">
                          <h4 className="text-sm font-semibold text-violet-700 mb-2 flex items-center gap-1">
                            📱 Device Distribution
                          </h4>
                          <div className="space-y-1">
                            {Object.entries(selectedCohort.criteria.statistics.deviceDistribution)
                              .sort(([,a], [,b]) => b - a)
                              .map(([device, count]) => (
                                <div key={device} className="flex items-center justify-between text-sm">
                                  <span className="text-slate-600 capitalize">{device}</span>
                                  <span className="font-medium text-violet-700">
                                    {count} ({Math.round((count / selectedCohort.size) * 100)}%)
                                  </span>
                                </div>
                              ))}
                          </div>
                        </div>
                      )}

                      {/* Acquisition Distribution */}
                      {selectedCohort.criteria.statistics.acquisitionDistribution && 
                       Object.keys(selectedCohort.criteria.statistics.acquisitionDistribution).length > 0 && (
                        <div className="p-4 bg-gradient-to-br from-amber-50 to-orange-50 rounded-xl border border-amber-200">
                          <h4 className="text-sm font-semibold text-amber-700 mb-2 flex items-center gap-1">
                            📊 Traffic Sources
                          </h4>
                          <div className="space-y-1">
                            {Object.entries(selectedCohort.criteria.statistics.acquisitionDistribution)
                              .sort(([,a], [,b]) => b - a)
                              .slice(0, 5)
                              .map(([source, count]) => (
                                <div key={source} className="flex items-center justify-between text-sm">
                                  <span className="text-slate-600 truncate max-w-[150px]">{source}</span>
                                  <span className="font-medium text-amber-700">
                                    {count} ({Math.round((count / selectedCohort.size) * 100)}%)
                                  </span>
                                </div>
                              ))}
                          </div>
                        </div>
                      )}

                      {/* Engagement Metrics */}
                      {(selectedCohort.criteria.statistics.avgSessionDuration || 
                        selectedCohort.criteria.statistics.avgSignalWeight) && (
                        <div className="p-4 bg-gradient-to-br from-rose-50 to-pink-50 rounded-xl border border-rose-200">
                          <h4 className="text-sm font-semibold text-rose-700 mb-2 flex items-center gap-1">
                            ⚡ Engagement Metrics
                          </h4>
                          <div className="space-y-2">
                            {selectedCohort.criteria.statistics.avgSessionDuration && (
                              <div className="flex items-center justify-between text-sm">
                                <span className="text-slate-600">Avg Session Duration</span>
                                <span className="font-medium text-rose-700">
                                  {Math.round(selectedCohort.criteria.statistics.avgSessionDuration)}s
                                </span>
                              </div>
                            )}
                            {selectedCohort.criteria.statistics.avgSignalWeight && (
                              <div className="flex items-center justify-between text-sm">
                                <span className="text-slate-600">Avg Signal Weight</span>
                                <span className="font-medium text-rose-700">
                                  {selectedCohort.criteria.statistics.avgSignalWeight.toFixed(1)}
                                </span>
                              </div>
                            )}
                          </div>
                        </div>
                      )}
                    </div>
                  )}

                  {/* Top Insights */}
                  {selectedCohort.criteria?.topInsights && selectedCohort.criteria.topInsights.length > 0 && (
                    <div className="mt-4 p-4 bg-gradient-to-br from-indigo-50 to-blue-50 rounded-xl border border-indigo-200">
                      <h4 className="text-sm font-semibold text-indigo-700 mb-3 flex items-center gap-2">
                        <Lightbulb className="w-4 h-4" />
                        Key Insights
                      </h4>
                      <ul className="space-y-2">
                        {selectedCohort.criteria.topInsights.map((insight, idx) => (
                          <li key={idx} className="flex items-start gap-2 text-sm text-slate-700">
                            <span className="text-indigo-500 font-medium">{idx + 1}.</span>
                            {insight}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>

                {/* Hypotheses */}
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                      <Lightbulb className="w-5 h-5 text-amber-500" />
                      AI-Generated Hypotheses
                    </h3>
                    <button
                      onClick={() => generateHypotheses(selectedCohort.id)}
                      disabled={isGeneratingHypotheses}
                      className="flex items-center gap-2 px-3 py-1.5 text-sm bg-amber-50 text-amber-700 rounded-xl hover:bg-amber-100 transition-all font-medium disabled:opacity-50"
                    >
                      {isGeneratingHypotheses ? (
                        <Loader2 className="w-4 h-4 animate-spin" />
                      ) : (
                        <Brain className="w-4 h-4" />
                      )}
                      {isGeneratingHypotheses ? 'Generating...' : 'Regenerate'}
                    </button>
                  </div>

                  {hypotheses.length === 0 ? (
                    <div className="bg-gradient-to-br from-amber-50 to-orange-50 rounded-2xl p-8 text-center border border-amber-200">
                      <Lightbulb className="w-10 h-10 mx-auto mb-3 text-amber-300" />
                      <p className="text-slate-600 mb-4">No hypotheses generated yet</p>
                      <button
                        onClick={() => generateHypotheses(selectedCohort.id)}
                        disabled={isGeneratingHypotheses}
                        className="text-sm text-amber-600 hover:text-amber-700 font-medium"
                      >
                        Generate hypotheses from behavioral patterns →
                      </button>
                    </div>
                  ) : (
                    <div className="space-y-3">
                      {hypotheses.map(hypothesis => (
                        <motion.div
                          key={hypothesis.id}
                          className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm"
                          initial={{ opacity: 0, y: 20 }}
                          animate={{ opacity: 1, y: 0 }}
                        >
                          <div
                            className="p-4 cursor-pointer hover:bg-slate-50 transition-colors"
                            onClick={() => setExpandedHypothesis(
                              expandedHypothesis === hypothesis.id ? null : hypothesis.id
                            )}
                          >
                            <div className="flex items-start justify-between gap-3">
                              <div className="flex-1">
                                <div className="flex items-center gap-2 mb-1">
                                  <h4 className="font-semibold text-slate-900">{hypothesis.title}</h4>
                                  <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                                    hypothesis.confidence >= 0.7 ? 'bg-green-100 text-green-700' :
                                    hypothesis.confidence >= 0.4 ? 'bg-amber-100 text-amber-700' :
                                    'bg-slate-100 text-slate-600'
                                  }`}>
                                    {Math.round(hypothesis.confidence * 100)}% confidence
                                  </span>
                                </div>
                                <p className="text-sm text-slate-600 line-clamp-2">{hypothesis.description}</p>
                              </div>
                              <div className="flex items-center gap-2">
                                {hypothesis.questions.length > 0 && (
                                  <span className="flex items-center gap-1 text-xs text-purple-600 bg-purple-50 px-2 py-1 rounded-lg">
                                    <HelpCircle className="w-3 h-3" />
                                    {hypothesis.questions.length} questions
                                  </span>
                                )}
                                {expandedHypothesis === hypothesis.id ? (
                                  <ChevronUp className="w-5 h-5 text-slate-400" />
                                ) : (
                                  <ChevronDown className="w-5 h-5 text-slate-400" />
                                )}
                              </div>
                            </div>
                          </div>

                          <AnimatePresence>
                            {expandedHypothesis === hypothesis.id && (
                              <motion.div
                                initial={{ height: 0, opacity: 0 }}
                                animate={{ height: 'auto', opacity: 1 }}
                                exit={{ height: 0, opacity: 0 }}
                                className="border-t border-slate-100"
                              >
                                <div className="p-4 bg-slate-50 space-y-4">
                                  {/* Evidence */}
                                  {hypothesis.evidence && (
                                    <div>
                                      <h5 className="text-sm font-semibold text-slate-700 mb-2">Supporting Evidence:</h5>
                                      <div className="text-sm text-slate-600 bg-white p-3 rounded-xl border border-slate-200">
                                        {typeof hypothesis.evidence === 'object' ? (
                                          <ul className="space-y-1">
                                            {Object.entries(hypothesis.evidence).map(([key, value]) => (
                                              <li key={key} className="flex items-start gap-2">
                                                <span className="text-slate-400">•</span>
                                                <span><strong className="capitalize">{key.replace(/_/g, ' ')}:</strong> {String(value)}</span>
                                              </li>
                                            ))}
                                          </ul>
                                        ) : (
                                          hypothesis.evidence
                                        )}
                                      </div>
                                    </div>
                                  )}

                                  {/* Interview Questions */}
                                  {hypothesis.questions.length > 0 && (
                                    <div>
                                      <h5 className="text-sm font-semibold text-purple-700 mb-2">Suggested Interview Questions:</h5>
                                      <ul className="space-y-2">
                                        {hypothesis.questions.map((q) => (
                                          <li key={q.id} className="text-sm bg-purple-50 p-3 rounded-xl border border-purple-200">
                                            <div className="flex items-start gap-2">
                                              <HelpCircle className="w-4 h-4 text-purple-500 mt-0.5 flex-shrink-0" />
                                              <div>
                                                <p className="text-slate-700 font-medium">{q.question}</p>
                                                {q.purpose && (
                                                  <p className="text-xs text-purple-600 mt-1">Purpose: {q.purpose}</p>
                                                )}
                                              </div>
                                            </div>
                                          </li>
                                        ))}
                                      </ul>
                                    </div>
                                  )}

                                  {/* Actions */}
                                  <div className="flex items-center gap-2 pt-2">
                                    <button
                                      onClick={(e) => {
                                        e.stopPropagation();
                                        scheduleInterviews(selectedCohort.id);
                                      }}
                                      className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors font-medium"
                                    >
                                      <MessageCircle className="w-3.5 h-3.5" />
                                      Start Interviews
                                    </button>
                                  </div>
                                </div>
                              </motion.div>
                            )}
                          </AnimatePresence>
                        </motion.div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Analyses */}
                <div className="space-y-4">
                  <h3 className="text-lg font-semibold text-slate-900">Recent Analyses</h3>
                  {analyses.length === 0 ? (
                    <div className="bg-gradient-to-br from-slate-50 to-slate-100 rounded-2xl p-8 text-center border border-slate-200">
                      <BarChart3 className="w-10 h-10 mx-auto mb-3 text-slate-300" />
                      <p className="text-slate-600 mb-4">No analyses yet</p>
                      <button
                        onClick={() => runAnalysis(selectedCohort.id)}
                        disabled={isAnalyzing}
                        className="text-sm text-blue-600 hover:text-blue-700 font-medium"
                      >
                        Run your first analysis →
                      </button>
                    </div>
                  ) : (
                    analyses.map(analysis => (
                      <motion.div
                        key={analysis.id}
                        className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm"
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                      >
                        <div className="flex items-center justify-between mb-4">
                          <div className="flex items-center gap-2">
                            <TrendingUp className="w-5 h-5 text-blue-600" />
                            <h4 className="font-semibold capitalize text-slate-900">{analysis.analysisType} Analysis</h4>
                          </div>
                          <div className="text-xs text-slate-500">
                            {new Date(analysis.createdAt).toLocaleDateString()}
                          </div>
                        </div>

                        {analysis.insights?.summary && (
                          <p className="text-slate-700 mb-5 leading-relaxed">{analysis.insights.summary}</p>
                        )}

                        <div className="space-y-4">
                          {analysis.insights?.trends && analysis.insights.trends.length > 0 && (
                            <div>
                              <h5 className="text-sm font-semibold text-emerald-600 mb-2">Trends:</h5>
                              <ul className="space-y-2">
                                {analysis.insights.trends.map((trend, idx) => (
                                  <li key={idx} className="text-sm text-slate-700 flex items-start gap-2 bg-emerald-50 p-3 rounded-xl border border-emerald-200">
                                    <span className="text-emerald-600 font-bold">↗</span>
                                    {trend}
                                  </li>
                                ))}
                              </ul>
                            </div>
                          )}

                          {analysis.insights?.recommendations && analysis.insights.recommendations.length > 0 && (
                            <div>
                              <h5 className="text-sm font-semibold text-blue-600 mb-2">Recommendations:</h5>
                              <ul className="space-y-2">
                                {analysis.insights.recommendations.map((rec, idx) => (
                                  <li key={idx} className="text-sm text-slate-700 flex items-start gap-2 bg-blue-50 p-3 rounded-xl border border-blue-200">
                                    <span className="text-blue-600 font-bold">→</span>
                                    {rec}
                                  </li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </div>

                        {analysis.metrics?.topEvents && analysis.metrics.topEvents.length > 0 && (
                          <div className="mt-5 pt-5 border-t border-slate-200">
                            <h5 className="text-sm font-semibold text-slate-900 mb-3">Top Events:</h5>
                            <div className="space-y-2">
                              {analysis.metrics.topEvents.slice(0, 5).map((event, idx) => (
                                <div key={idx} className="flex items-center justify-between text-sm bg-slate-50 p-3 rounded-xl">
                                  <span className="text-slate-700 font-medium">{event.event}</span>
                                  <span className="text-slate-900 font-bold font-mono">{event.count}</span>
                                </div>
                              ))}
                            </div>
                          </div>
                        )}
                      </motion.div>
                    ))
                  )}
                </div>
              </div>
            ) : (
              <div className="flex items-center justify-center h-96">
                <div className="text-center">
                  <Users className="w-16 h-16 mx-auto mb-4 text-slate-300" />
                  <p className="text-slate-600 mb-2">Select a cohort to view details</p>
                  <p className="text-sm text-slate-400">Or create one from the Funnels page</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
