import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getProjectWithAccess } from '@/lib/auth';
import { junoHardcodedInsights } from '@/lib/hardcoded-insights-juno';

// ---------------------------------------------------------------------------
// Map hardcoded insights → ticket shape for juno-demo
// ---------------------------------------------------------------------------

function severityScore(severity: string) {
  if (severity === 'critical') return 90;
  if (severity === 'high') return 70;
  return 50;
}

function getDemoTickets() {
  const now = new Date().toISOString();
  const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

  return junoHardcodedInsights.criticalIssues.map((issue, i) => {
    const score = severityScore(issue.severity) + Math.max(0, 10 - i * 3);
    const atRisk = issue.sessionIds.length;
    return {
      id: `juno-insight-${i + 1}`,
      projectId: 'juno-demo',
      title: issue.title,
      description: issue.description,
      severity: issue.severity,
      category: 'ux_friction',
      effort: 'medium',
      recommendation: issue.recommendation,
      compositeScore: score,
      evidence: {
        sessionIds: issue.sessionIds,
        sessionNames: issue.sessionNames,
        conversationIds: issue.sessionIds,
        quotes: [],
      },
      scoreBreakdown: { frequency: 20, churn: 20, severity: score > 80 ? 20 : 14, recency: 16 },
      churnImpact: { atRiskUsers: atRisk, avgRiskScore: score, userIds: issue.sessionIds },
      trending: { firstSeen: oneWeekAgo, lastSeen: now, weeklyCounts: [atRisk, 0, 0, 0], trend: 'rising' },
      jiraMarkdown: `**Title:** ${issue.title}\n**Severity:** ${issue.severity.toUpperCase()} | **Score:** ${score}/100\n\n**Description:**\n${issue.description.slice(0, 300)}...\n\n**Recommendation:**\n${issue.recommendation.slice(0, 300)}...\n\n---\n_Generated by Tranzmit Intelligence_`,
      status: 'open',
      synthesizedAt: now,
      createdAt: now,
      updatedAt: now,
    };
  });
}

// ---------------------------------------------------------------------------
// GET /api/tickets?projectId=...
// ---------------------------------------------------------------------------

export async function GET(request: NextRequest) {
  const projectId = request.nextUrl.searchParams.get('projectId');

  if (!projectId) {
    return NextResponse.json({ error: 'Project ID required' }, { status: 400 });
  }

  // Demo project — return hardcoded tickets without auth
  if (projectId === 'juno-demo') {
    const tickets = getDemoTickets();
    const critical = tickets.filter((t) => t.severity === 'critical').length;
    const high = tickets.filter((t) => t.severity === 'high').length;
    const medium = tickets.filter((t) => t.severity === 'medium').length;

    return NextResponse.json({
      tickets,
      stats: {
        total: tickets.length,
        critical,
        high,
        medium,
        lastSynthesized: tickets[0]?.synthesizedAt ?? null,
      },
    });
  }

  try {
    // Auth check
    const projectAccess = await getProjectWithAccess(projectId);
    if (!projectAccess) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Fetch tickets ordered by composite score
    const tickets = await prisma.ticket.findMany({
      where: { projectId },
      orderBy: { compositeScore: 'desc' },
    });

    const critical = tickets.filter((t) => t.severity === 'critical').length;
    const high = tickets.filter((t) => t.severity === 'high').length;
    const medium = tickets.filter((t) => t.severity === 'medium').length;
    const lastSynthesized =
      tickets.length > 0 ? tickets[0].synthesizedAt?.toISOString() ?? null : null;

    return NextResponse.json({
      tickets,
      stats: {
        total: tickets.length,
        critical,
        high,
        medium,
        lastSynthesized,
      },
    });
  } catch (error) {
    console.error('[Tickets GET] Error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch tickets' },
      { status: 500 },
    );
  }
}
