import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getProjectWithAccess } from '@/lib/auth';

// ---------------------------------------------------------------------------
// Hardcoded demo tickets for juno-demo
// ---------------------------------------------------------------------------

function getDemoTickets() {
  const now = new Date().toISOString();
  const threeDaysAgo = new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString();
  const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

  return [
    {
      id: 'juno-ticket-1',
      projectId: 'juno-demo',
      title: 'Dark mode toggle is undiscoverable — users abandon settings flow',
      description:
        'Multiple users report being unable to find the dark mode setting despite actively searching for it. Session replays show users scrolling through settings repeatedly, opening submenus, and eventually giving up. This is causing frustration in evening usage sessions and contributing to reduced session duration after 8pm.',
      severity: 'critical',
      category: 'ux_friction',
      effort: 'low',
      recommendation:
        'Move dark mode toggle to the top-level settings page and add a quick-toggle in the app header. Consider auto-detecting system preference on first launch.',
      compositeScore: 92,
      evidence: {
        sessionIds: ['ses-juno-101', 'ses-juno-102', 'ses-juno-103', 'ses-juno-104'],
        conversationIds: ['conv-juno-201', 'conv-juno-202'],
        quotes: [
          'I looked everywhere for the dark mode toggle — it should be right there in settings, not buried three levels deep.',
          'I only use Juno at night and the bright white screen is killing my eyes. I almost deleted the app.',
        ],
      },
      scoreBreakdown: { frequency: 20, churn: 24, severity: 20, recency: 20 },
      churnImpact: { atRiskUsers: 4, avgRiskScore: 78, userIds: ['user-301', 'user-302', 'user-303', 'user-304'] },
      trending: {
        firstSeen: oneWeekAgo,
        lastSeen: now,
        weeklyCounts: [3, 1, 0, 0],
        trend: 'rising',
      },
      jiraMarkdown: `**Title:** Dark mode toggle is undiscoverable — users abandon settings flow\n**Severity:** CRITICAL | **Category:** ux_friction | **Score:** 92/100\n**Effort:** low\n\n**Description:**\nMultiple users report being unable to find the dark mode setting despite actively searching for it.\n\n**Evidence:**\n- 4 session(s) affected\n- 2 conversation(s) mentioning this\n- 4 at-risk user(s)\n\n**User Quotes:**\n> I looked everywhere for the dark mode toggle — it should be right there in settings, not buried three levels deep.\n> I only use Juno at night and the bright white screen is killing my eyes. I almost deleted the app.\n\n**Score Breakdown:**\nFrequency: 20/30 | Churn: 24/30 | Severity: 20/20 | Recency: 20/20\n\n**Recommendation:**\nMove dark mode toggle to the top-level settings page and add a quick-toggle in the app header.\n\n---\n_Generated by Tranzmit Intelligence_`,
      status: 'open',
      synthesizedAt: now,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'juno-ticket-2',
      projectId: 'juno-demo',
      title: 'App freezes mid-journal entry causing complete data loss',
      description:
        'Users are experiencing hard freezes during journaling sessions, particularly when entries exceed ~500 words. The freeze results in total loss of the entry with no auto-save recovery. This is the single most emotionally damaging bug — users who lose a deeply personal journal entry rarely return.',
      severity: 'critical',
      category: 'bug',
      effort: 'medium',
      recommendation:
        'Implement auto-save every 10 seconds with local IndexedDB backup. Add a crash recovery screen that restores the last saved draft on next launch.',
      compositeScore: 88,
      evidence: {
        sessionIds: ['ses-juno-105', 'ses-juno-106', 'ses-juno-107'],
        conversationIds: ['conv-juno-203', 'conv-juno-204', 'conv-juno-205'],
        quotes: [
          'The app just froze and I lost my whole journal entry. I was pouring my heart out and it just vanished.',
          'I spent 20 minutes writing about my day and poof — gone. I literally cried.',
          'After losing two entries I stopped using the app entirely. I can\'t trust it with my thoughts.',
        ],
      },
      scoreBreakdown: { frequency: 15, churn: 30, severity: 20, recency: 20 },
      churnImpact: { atRiskUsers: 5, avgRiskScore: 85, userIds: ['user-305', 'user-306', 'user-307', 'user-308', 'user-309'] },
      trending: {
        firstSeen: oneWeekAgo,
        lastSeen: threeDaysAgo,
        weeklyCounts: [2, 1, 0, 0],
        trend: 'rising',
      },
      jiraMarkdown: `**Title:** App freezes mid-journal entry causing complete data loss\n**Severity:** CRITICAL | **Category:** bug | **Score:** 88/100\n**Effort:** medium\n\n**Description:**\nUsers are experiencing hard freezes during journaling sessions, particularly when entries exceed ~500 words.\n\n**Evidence:**\n- 3 session(s) affected\n- 3 conversation(s) mentioning this\n- 5 at-risk user(s)\n\n**User Quotes:**\n> The app just froze and I lost my whole journal entry. I was pouring my heart out and it just vanished.\n> I spent 20 minutes writing about my day and poof — gone. I literally cried.\n> After losing two entries I stopped using the app entirely. I can't trust it with my thoughts.\n\n**Score Breakdown:**\nFrequency: 15/30 | Churn: 30/30 | Severity: 20/20 | Recency: 20/20\n\n**Recommendation:**\nImplement auto-save every 10 seconds with local IndexedDB backup.\n\n---\n_Generated by Tranzmit Intelligence_`,
      status: 'open',
      synthesizedAt: now,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'juno-ticket-3',
      projectId: 'juno-demo',
      title: 'No way to export or share journal entries — users feel locked in',
      description:
        'Users want to share meaningful entries with their therapist, partner, or save them externally. The lack of any export mechanism creates anxiety about data portability and is cited as a reason for not committing to long-term use of the app.',
      severity: 'high',
      category: 'feature_gap',
      effort: 'medium',
      recommendation:
        'Add export options: PDF for single entries, bulk CSV/JSON export for all data, and a "Share with therapist" flow that generates a read-only link.',
      compositeScore: 74,
      evidence: {
        sessionIds: ['ses-juno-108', 'ses-juno-109'],
        conversationIds: ['conv-juno-206', 'conv-juno-207', 'conv-juno-208'],
        quotes: [
          'My therapist asked me to share my journal entries but there\'s literally no way to get them out of the app.',
          'I want to know my data is mine. If you shut down tomorrow I lose years of journaling.',
        ],
      },
      scoreBreakdown: { frequency: 10, churn: 18, severity: 14, recency: 16 },
      churnImpact: { atRiskUsers: 3, avgRiskScore: 62, userIds: ['user-310', 'user-311', 'user-312'] },
      trending: {
        firstSeen: oneWeekAgo,
        lastSeen: threeDaysAgo,
        weeklyCounts: [2, 2, 1, 0],
        trend: 'stable',
      },
      jiraMarkdown: `**Title:** No way to export or share journal entries — users feel locked in\n**Severity:** HIGH | **Category:** feature_gap | **Score:** 74/100\n**Effort:** medium\n\n**Description:**\nUsers want to share meaningful entries with their therapist, partner, or save them externally.\n\n**Evidence:**\n- 2 session(s) affected\n- 3 conversation(s) mentioning this\n- 3 at-risk user(s)\n\n**User Quotes:**\n> My therapist asked me to share my journal entries but there's literally no way to get them out of the app.\n> I want to know my data is mine. If you shut down tomorrow I lose years of journaling.\n\n**Score Breakdown:**\nFrequency: 10/30 | Churn: 18/30 | Severity: 14/20 | Recency: 16/20\n\n**Recommendation:**\nAdd export options: PDF for single entries, bulk CSV/JSON export for all data.\n\n---\n_Generated by Tranzmit Intelligence_`,
      status: 'open',
      synthesizedAt: now,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'juno-ticket-4',
      projectId: 'juno-demo',
      title: 'Push notification reminders are too aggressive — users mute the app',
      description:
        'Users receive 2-3 daily journaling reminders with no way to customize frequency or timing. Several users reported muting all notifications for Juno, which then causes them to forget about the app entirely and lapse into inactivity.',
      severity: 'high',
      category: 'retention',
      effort: 'low',
      recommendation:
        'Add notification preference screen during onboarding: frequency (daily/weekly/none), preferred time, and motivational vs. simple reminder style. Default to 1x daily at 8pm.',
      compositeScore: 68,
      evidence: {
        sessionIds: ['ses-juno-110'],
        conversationIds: ['conv-juno-209', 'conv-juno-210'],
        quotes: [
          'Three notifications a day? I muted Juno and then forgot it existed for two weeks.',
          'I love the app but the constant reminders made me feel guilty, not motivated.',
        ],
      },
      scoreBreakdown: { frequency: 10, churn: 12, severity: 14, recency: 16 },
      churnImpact: { atRiskUsers: 2, avgRiskScore: 58, userIds: ['user-313', 'user-314'] },
      trending: {
        firstSeen: oneWeekAgo,
        lastSeen: threeDaysAgo,
        weeklyCounts: [1, 1, 1, 1],
        trend: 'stable',
      },
      jiraMarkdown: `**Title:** Push notification reminders are too aggressive — users mute the app\n**Severity:** HIGH | **Category:** retention | **Score:** 68/100\n**Effort:** low\n\n**Description:**\nUsers receive 2-3 daily journaling reminders with no way to customize frequency or timing.\n\n**Evidence:**\n- 1 session(s) affected\n- 2 conversation(s) mentioning this\n- 2 at-risk user(s)\n\n**User Quotes:**\n> Three notifications a day? I muted Juno and then forgot it existed for two weeks.\n> I love the app but the constant reminders made me feel guilty, not motivated.\n\n**Score Breakdown:**\nFrequency: 10/30 | Churn: 12/30 | Severity: 14/20 | Recency: 16/20\n\n**Recommendation:**\nAdd notification preference screen during onboarding.\n\n---\n_Generated by Tranzmit Intelligence_`,
      status: 'open',
      synthesizedAt: now,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'juno-ticket-5',
      projectId: 'juno-demo',
      title: 'Onboarding skips mood-tracking tutorial — users never discover core feature',
      description:
        'The onboarding flow jumps straight to journaling without introducing the mood-tracking and insights features. Users who discover mood tracking later express surprise and delight, but analytics show 60% of users never find it. This represents a massive untapped engagement lever.',
      severity: 'medium',
      category: 'onboarding',
      effort: 'low',
      recommendation:
        'Add a 3-step interactive tutorial after first journal entry: (1) show mood tracking, (2) demonstrate weekly insights, (3) highlight streak rewards. A/B test tooltip vs. coach-mark approach.',
      compositeScore: 55,
      evidence: {
        sessionIds: ['ses-juno-111', 'ses-juno-112'],
        conversationIds: ['conv-juno-211'],
        quotes: [
          'Wait, there\'s mood tracking? I\'ve been using Juno for a month and never saw that. That\'s actually really cool.',
        ],
      },
      scoreBreakdown: { frequency: 10, churn: 6, severity: 8, recency: 16 },
      churnImpact: { atRiskUsers: 1, avgRiskScore: 45, userIds: ['user-315'] },
      trending: {
        firstSeen: oneWeekAgo,
        lastSeen: now,
        weeklyCounts: [1, 0, 1, 0],
        trend: 'rising',
      },
      jiraMarkdown: `**Title:** Onboarding skips mood-tracking tutorial — users never discover core feature\n**Severity:** MEDIUM | **Category:** onboarding | **Score:** 55/100\n**Effort:** low\n\n**Description:**\nThe onboarding flow jumps straight to journaling without introducing the mood-tracking and insights features.\n\n**Evidence:**\n- 2 session(s) affected\n- 1 conversation(s) mentioning this\n- 1 at-risk user(s)\n\n**User Quotes:**\n> Wait, there's mood tracking? I've been using Juno for a month and never saw that. That's actually really cool.\n\n**Score Breakdown:**\nFrequency: 10/30 | Churn: 6/30 | Severity: 8/20 | Recency: 16/20\n\n**Recommendation:**\nAdd a 3-step interactive tutorial after first journal entry.\n\n---\n_Generated by Tranzmit Intelligence_`,
      status: 'open',
      synthesizedAt: now,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

// ---------------------------------------------------------------------------
// GET /api/tickets?projectId=...
// ---------------------------------------------------------------------------

export async function GET(request: NextRequest) {
  const projectId = request.nextUrl.searchParams.get('projectId');

  if (!projectId) {
    return NextResponse.json({ error: 'Project ID required' }, { status: 400 });
  }

  // Demo project — return hardcoded tickets without auth
  if (projectId === 'juno-demo') {
    const tickets = getDemoTickets();
    const critical = tickets.filter((t) => t.severity === 'critical').length;
    const high = tickets.filter((t) => t.severity === 'high').length;
    const medium = tickets.filter((t) => t.severity === 'medium').length;

    return NextResponse.json({
      tickets,
      stats: {
        total: tickets.length,
        critical,
        high,
        medium,
        lastSynthesized: tickets[0]?.synthesizedAt ?? null,
      },
    });
  }

  try {
    // Auth check
    const projectAccess = await getProjectWithAccess(projectId);
    if (!projectAccess) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Fetch tickets ordered by composite score
    const tickets = await prisma.ticket.findMany({
      where: { projectId },
      orderBy: { compositeScore: 'desc' },
    });

    const critical = tickets.filter((t) => t.severity === 'critical').length;
    const high = tickets.filter((t) => t.severity === 'high').length;
    const medium = tickets.filter((t) => t.severity === 'medium').length;
    const lastSynthesized =
      tickets.length > 0 ? tickets[0].synthesizedAt?.toISOString() ?? null : null;

    return NextResponse.json({
      tickets,
      stats: {
        total: tickets.length,
        critical,
        high,
        medium,
        lastSynthesized,
      },
    });
  } catch (error) {
    console.error('[Tickets GET] Error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch tickets' },
      { status: 500 },
    );
  }
}
