'use client';

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Link from 'next/link';
import {
  Loader2,
  RefreshCw,
  ChevronDown,
  MessageCircle,
  PlayCircle,
  ArrowRight,
  Ticket,
  Check,
} from 'lucide-react';

interface PrioritizedIssue {
  id: string;
  title: string;
  description: string;
  severity: 'critical' | 'high' | 'medium';
  priority_score: number;
  category: string;
  evidence: {
    session_count: number;
    conversation_count: number;
    sample_quotes: string[];
  };
  recommendation: string;
  effort: 'low' | 'medium' | 'high';
  linked_sessions?: string[];
  linked_conversations?: string[];
}

interface UserGoal {
  goal: string;
  success_rate: string;
  blockers: string[];
}

interface QuickWin {
  action: string;
  impact: string;
  effort: 'low' | 'medium';
}

interface ProductHealth {
  overall_score: number;
  sentiment_trend: 'improving' | 'stable' | 'declining';
  top_strength: string;
  top_risk: string;
}

interface DashboardData {
  insights: {
    prioritized_issues: PrioritizedIssue[];
    user_goals: UserGoal[];
    quick_wins: QuickWin[];
    product_health: ProductHealth;
    executive_summary: string;
  } | null;
  stats: {
    sessions_analyzed: number;
    conversations_analyzed: number;
    avg_session_rating: number | null;
    avg_conversation_satisfaction: number | null;
    last_updated: string | null;
  };
}

const categoryLabels: Record<string, string> = {
  ux_friction: 'UX Friction',
  feature_gap: 'Feature Gap',
  bug: 'Bug',
  confusion: 'Confusion',
  performance: 'Performance',
  onboarding: 'Onboarding',
  retention: 'Retention',
};

function IssueCard({ issue, isExpanded, onToggle }: {
  issue: PrioritizedIssue;
  isExpanded: boolean;
  onToggle: () => void;
}) {
  const [copied, setCopied] = useState(false);

  const generateJiraTicket = () => {
    const ticket = `**Title:** ${issue.title}

**Severity:** ${issue.severity.toUpperCase()}
**Category:** ${categoryLabels[issue.category] || issue.category}
**Priority Score:** ${issue.priority_score}/100
**Effort:** ${issue.effort}

**Description:**
${issue.description}

**Evidence:**
- ${issue.evidence.session_count} session(s) affected
- ${issue.evidence.conversation_count} conversation(s) mentioning this

**User Quotes:**
${issue.evidence.sample_quotes.map(q => `> "${q}"`).join('\n')}

**Recommendation:**
${issue.recommendation}

---
_Generated by Tranzmit_`;

    navigator.clipboard.writeText(ticket);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const firstQuote = issue.evidence.sample_quotes[0];

  return (
    <div className="bg-white dark:bg-[#141414] rounded-xl overflow-hidden border border-gray-200 dark:border-transparent">
      <button
        onClick={onToggle}
        className="w-full p-5 text-left hover:bg-gray-50 dark:hover:bg-[#1a1a1a] transition-colors"
      >
        <div className="flex items-start justify-between gap-4">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-2">
              <span className={`w-2 h-2 rounded-full shrink-0 ${
                issue.severity === 'critical' ? 'bg-red-500' :
                issue.severity === 'high' ? 'bg-orange-500' : 'bg-yellow-500'
              }`} />
              <span className="text-gray-900 dark:text-white font-medium">{issue.title}</span>
              <span className="text-gray-400 dark:text-[#444] text-xs">{categoryLabels[issue.category] || issue.category}</span>
            </div>
            {firstQuote && (
              <p className="text-gray-500 dark:text-[#666] text-sm italic pl-4 border-l-2 border-gray-300 dark:border-[#333] line-clamp-1">
                &ldquo;{firstQuote}&rdquo;
              </p>
            )}
          </div>
          <div className="flex items-center gap-4 shrink-0">
            <span className="text-gray-400 dark:text-[#444] text-xs">{issue.evidence.session_count + issue.evidence.conversation_count} sources</span>
            <ChevronDown className={`w-4 h-4 text-gray-400 dark:text-[#666] transition-transform ${isExpanded ? 'rotate-180' : ''}`} />
          </div>
        </div>
      </button>

      <AnimatePresence>
        {isExpanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-5 border-t border-gray-200 dark:border-[#222]">
              <p className="text-gray-600 dark:text-[#888] text-sm mt-4">{issue.description}</p>

              {issue.evidence.sample_quotes.length > 0 && (
                <div className="mt-5">
                  <p className="text-gray-400 dark:text-[#666] text-xs uppercase tracking-wide mb-3">Verbatim User Quotes</p>
                  <div className="space-y-2">
                    {issue.evidence.sample_quotes.map((quote, idx) => (
                      <div key={idx} className="border-l-2 border-blue-500 pl-4 py-2">
                        <p className="text-gray-800 dark:text-white text-sm">&ldquo;{quote}&rdquo;</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div className="mt-5 bg-emerald-50 dark:bg-[#0d1f17] rounded-lg p-4">
                <p className="text-gray-500 dark:text-[#666] text-xs uppercase tracking-wide mb-2">Recommendation</p>
                <p className="text-emerald-700 dark:text-emerald-400 text-sm">{issue.recommendation}</p>
              </div>

              <div className="mt-5 flex items-center justify-between">
                <div className="flex items-center gap-4">
                  {(issue.linked_sessions?.length || 0) > 0 && (
                    <Link
                      href={`/dashboard/session-insights?highlight=${issue.linked_sessions?.[0]}`}
                      className="text-sm text-gray-500 dark:text-[#888] hover:text-gray-900 dark:hover:text-white flex items-center gap-1.5 transition-colors"
                    >
                      <PlayCircle className="w-4 h-4" />
                      View Sessions
                      <ArrowRight className="w-3 h-3" />
                    </Link>
                  )}
                  {(issue.linked_conversations?.length || 0) > 0 && (
                    <Link
                      href={`/dashboard/hypotheses?conversationId=${issue.linked_conversations?.[0]}`}
                      className="text-sm text-gray-500 dark:text-[#888] hover:text-gray-900 dark:hover:text-white flex items-center gap-1.5 transition-colors"
                    >
                      <MessageCircle className="w-4 h-4" />
                      View Conversations
                      <ArrowRight className="w-3 h-3" />
                    </Link>
                  )}
                </div>

                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    generateJiraTicket();
                  }}
                  className="flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-full bg-gray-900 dark:bg-white text-white dark:text-black hover:bg-gray-800 dark:hover:bg-gray-100 transition-colors"
                >
                  {copied ? (
                    <>
                      <Check className="w-4 h-4" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Ticket className="w-4 h-4" />
                      Create Jira Ticket
                    </>
                  )}
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function DashboardPage() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSynthesizing, setIsSynthesizing] = useState(false);
  const [expandedIssue, setExpandedIssue] = useState<string | null>(null);
  const [projectId, setProjectId] = useState<string>('');

  useEffect(() => {
    const initializeProject = async () => {
      let currentProjectId = localStorage.getItem('currentProjectId');

      if (!currentProjectId) {
        try {
          const response = await fetch('/api/projects');
          const result = await response.json();
          if (result.projects && result.projects.length > 0) {
            currentProjectId = result.projects[0].id;
            localStorage.setItem('currentProjectId', currentProjectId as string);
          }
        } catch (err) {
          console.error('Failed to fetch projects:', err);
        }
      }

      if (currentProjectId) {
        setProjectId(currentProjectId);
        loadDashboard(currentProjectId);
      } else {
        setIsLoading(false);
      }
    };

    initializeProject();
  }, []);

  const loadDashboard = async (projId: string, forceRefresh = false) => {
    if (forceRefresh) {
      setIsSynthesizing(true);
    } else {
      setIsLoading(true);
    }

    try {
      const response = await fetch(`/api/dashboard/synthesize?projectId=${projId}`);
      const result = await response.json();

      if (response.ok) {
        setData(result);
        if (result.insights?.prioritized_issues?.[0]) {
          setExpandedIssue(result.insights.prioritized_issues[0].id);
        }
      }
    } catch (error) {
      console.error('Failed to load dashboard:', error);
    } finally {
      setIsLoading(false);
      setIsSynthesizing(false);
    }
  };

  const handleRefresh = () => {
    if (projectId) {
      loadDashboard(projectId, true);
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-[#0a0a0a] flex items-center justify-center">
        <Loader2 className="w-5 h-5 animate-spin text-gray-900 dark:text-white" />
      </div>
    );
  }

  const insights = data?.insights;
  const stats = data?.stats;

  if (!insights || insights.prioritized_issues.length === 0) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-[#0a0a0a] p-8">
        <h1 className="text-xl font-medium text-gray-900 dark:text-white mb-2">Product Insights</h1>
        <p className="text-gray-500 dark:text-[#666] text-sm mb-12">Combine qualitative interviews with quantitative session data</p>

        <div className="max-w-sm">
          <p className="text-gray-500 dark:text-[#666] text-sm mb-6">No data yet. Sync sessions or upload conversations to get started.</p>
          <div className="flex items-center gap-3">
            <Link
              href="/dashboard/session-insights"
              className="px-5 py-2.5 text-sm font-medium bg-white dark:bg-[#141414] text-gray-900 dark:text-white rounded-full hover:bg-gray-100 dark:hover:bg-[#1a1a1a] transition-colors border border-gray-200 dark:border-transparent"
            >
              Sync Sessions
            </Link>
            <Link
              href="/dashboard/interviews"
              className="px-5 py-2.5 text-sm font-medium bg-gray-900 dark:bg-white text-white dark:text-black rounded-full hover:bg-gray-800 dark:hover:bg-gray-100 transition-colors"
            >
              Upload Conversations
            </Link>
          </div>
        </div>
      </div>
    );
  }

  const criticalCount = insights.prioritized_issues.filter(i => i.severity === 'critical').length;
  const highCount = insights.prioritized_issues.filter(i => i.severity === 'high').length;

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-[#0a0a0a]">
      {/* Header */}
      <div className="px-8 pt-8 pb-8">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-xl font-medium text-gray-900 dark:text-white">Product Insights</h1>
            <p className="text-gray-500 dark:text-[#666] text-sm mt-1">Combine qualitative interviews with quantitative session data</p>
          </div>
          <button
            onClick={handleRefresh}
            disabled={isSynthesizing}
            className="px-5 py-2.5 text-sm font-medium bg-gray-900 dark:bg-white text-white dark:text-black rounded-full hover:bg-gray-800 dark:hover:bg-gray-100 transition-colors disabled:opacity-50 flex items-center gap-2"
          >
            <RefreshCw className={`w-4 h-4 ${isSynthesizing ? 'animate-spin' : ''}`} />
            {isSynthesizing ? 'Analyzing...' : 'Refresh'}
          </button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="px-8 pb-8">
        <div className="grid grid-cols-4 gap-4">
          <div className="bg-white dark:bg-[#141414] rounded-xl p-5 border border-gray-200 dark:border-transparent">
            <p className="text-gray-500 dark:text-[#666] text-sm mb-2">Health Score</p>
            <div className="flex items-baseline gap-1">
              <span className="text-4xl font-medium text-gray-900 dark:text-white">{insights.product_health.overall_score}</span>
              <span className="text-gray-400 dark:text-[#666]">/10</span>
              <span className={`ml-2 text-sm ${
                insights.product_health.sentiment_trend === 'improving' ? 'text-emerald-500' :
                insights.product_health.sentiment_trend === 'declining' ? 'text-red-500' : 'text-gray-400'
              }`}>
                {insights.product_health.sentiment_trend === 'improving' ? '↑' :
                 insights.product_health.sentiment_trend === 'declining' ? '↓' : '—'}
              </span>
            </div>
          </div>
          <div className="bg-white dark:bg-[#141414] rounded-xl p-5 border border-gray-200 dark:border-transparent">
            <p className="text-gray-500 dark:text-[#666] text-sm mb-2">Critical Issues</p>
            <div className="flex items-baseline gap-2">
              <span className="text-4xl font-medium text-gray-900 dark:text-white">{criticalCount}</span>
              {criticalCount > 0 && <span className="text-red-500 text-sm">needs attention</span>}
            </div>
          </div>
          <div className="bg-white dark:bg-[#141414] rounded-xl p-5 border border-gray-200 dark:border-transparent">
            <p className="text-gray-500 dark:text-[#666] text-sm mb-2">Sessions Analyzed</p>
            <div className="flex items-baseline gap-2">
              <span className="text-4xl font-medium text-gray-900 dark:text-white">{stats?.sessions_analyzed || 0}</span>
              <span className="text-xs text-blue-600 dark:text-blue-400 font-medium px-2 py-0.5 rounded bg-blue-100 dark:bg-blue-500/10">QUANT</span>
            </div>
          </div>
          <div className="bg-white dark:bg-[#141414] rounded-xl p-5 border border-gray-200 dark:border-transparent">
            <p className="text-gray-500 dark:text-[#666] text-sm mb-2">Conversations</p>
            <div className="flex items-baseline gap-2">
              <span className="text-4xl font-medium text-gray-900 dark:text-white">{stats?.conversations_analyzed || 0}</span>
              <span className="text-xs text-purple-600 dark:text-purple-400 font-medium px-2 py-0.5 rounded bg-purple-100 dark:bg-purple-500/10">QUAL</span>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="px-8 pb-8">
        <div className="grid grid-cols-3 gap-6">
          {/* Issues */}
          <div className="col-span-2">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-blue-500" />
                <h2 className="text-gray-900 dark:text-white font-medium">Prioritized Issues</h2>
              </div>
              <span className="text-xs text-gray-400 dark:text-[#666]">{insights.prioritized_issues.length} issues found</span>
            </div>
            <div className="space-y-2">
              {insights.prioritized_issues.map((issue) => (
                <IssueCard
                  key={issue.id}
                  issue={issue}
                  isExpanded={expandedIssue === issue.id}
                  onToggle={() => setExpandedIssue(expandedIssue === issue.id ? null : issue.id)}
                />
              ))}
            </div>
          </div>

          {/* Sidebar */}
          <div className="space-y-4">
            {/* Executive Summary */}
            <div className="bg-white dark:bg-[#141414] rounded-xl p-5 border border-gray-200 dark:border-transparent">
              <div className="flex items-center gap-2 mb-3">
                <span className="w-2 h-2 rounded-full bg-purple-500" />
                <h3 className="text-gray-900 dark:text-white font-medium text-sm">Summary</h3>
              </div>
              <p className="text-gray-600 dark:text-[#888] text-sm leading-relaxed">{insights.executive_summary}</p>
            </div>

            {/* Quick Wins */}
            <div className="bg-white dark:bg-[#141414] rounded-xl p-5 border border-gray-200 dark:border-transparent">
              <div className="flex items-center gap-2 mb-4">
                <span className="w-2 h-2 rounded-full bg-emerald-500" />
                <h3 className="text-gray-900 dark:text-white font-medium text-sm">Quick Wins</h3>
              </div>
              <div className="space-y-3">
                {insights.quick_wins.map((win, idx) => (
                  <div key={idx} className="flex items-start gap-3">
                    <span className="text-gray-400 dark:text-[#666] text-sm">{idx + 1}.</span>
                    <div>
                      <p className="text-gray-800 dark:text-white text-sm">{win.action}</p>
                      <p className="text-emerald-600 dark:text-emerald-400 text-xs mt-0.5">{win.impact}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Strengths & Risks */}
            <div className="bg-white dark:bg-[#141414] rounded-xl p-5 border border-gray-200 dark:border-transparent">
              <div className="mb-4">
                <p className="text-emerald-600 dark:text-emerald-400 text-xs font-medium mb-1">Top Strength</p>
                <p className="text-gray-600 dark:text-[#888] text-sm">{insights.product_health.top_strength}</p>
              </div>
              <div>
                <p className="text-red-600 dark:text-red-400 text-xs font-medium mb-1">Top Risk</p>
                <p className="text-gray-600 dark:text-[#888] text-sm">{insights.product_health.top_risk}</p>
              </div>
            </div>

            {/* User Goals */}
            <div className="bg-white dark:bg-[#141414] rounded-xl p-5 border border-gray-200 dark:border-transparent">
              <div className="flex items-center gap-2 mb-4">
                <span className="w-2 h-2 rounded-full bg-orange-500" />
                <h3 className="text-gray-900 dark:text-white font-medium text-sm">User Goals</h3>
              </div>
              <div className="space-y-3">
                {insights.user_goals.map((goal, idx) => (
                  <div key={idx} className="flex items-center justify-between">
                    <span className="text-gray-600 dark:text-[#888] text-sm truncate flex-1 mr-3">{goal.goal}</span>
                    <span className={`text-xs font-medium ${
                      goal.success_rate.toLowerCase().includes('high') || goal.success_rate.toLowerCase().includes('success')
                        ? 'text-emerald-600 dark:text-emerald-400'
                        : goal.success_rate.toLowerCase().includes('low') || goal.success_rate.toLowerCase().includes('fail')
                        ? 'text-red-600 dark:text-red-400'
                        : 'text-orange-600 dark:text-orange-400'
                    }`}>
                      {goal.success_rate}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
